apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-myapp
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/emrekardaslar/argocd-myapp-config.git  # Your Git repo
    targetRevision: main
    path: manifests  # Folder inside your Git repo containing YAML files
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
