apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-myapp
  labels:
    app: argocd-myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-myapp
  template:
    metadata:
      labels:
        app: argocd-myapp
    spec:
      containers:
      - name: argocd-myapp
        image: emrekardaslar/argocd-myapp:latest  # Your Docker image
        ports:
        - containerPort: 5041  # The port your .NET app runs on
