apiVersion: v1
kind: Service
metadata:
  name: argocd-myapp
spec:
  type: LoadBalancer  # Makes the service accessible externally
  selector:
    app: argocd-myapp
  ports:
  - protocol: TCP
    port: 80  # External port
    targetPort: 5000  # Internal app port
